env:
  browser: true
  es2021: true
  es2022: true
extends:
  - ../../.eslintrc.react.yml
rules:
  # Disable for convenience
  react/display-name: off
  # Disable for convenience
  react/prop-types: off
